### PR TITLE
feat(history): complete support for history.push API

### PR DESCRIPTION
**Pull request by qti3e**
ISSUES CLOSED: 813

- [x] There exists an issue discussing the need for this PR
- [x] I added new tests for the issue I fixed or built
- [x] I used `pnpm run commit` instead of `git commit`

### CODE REVIEW

**Comment by jvanbruegge** [comment]
This is pretty much a perfect PR, small, with a test, has an outstanding issue and CI passes. Thank you a lot!

**Comment by jvanbruegge** [comment]
Just waiting for a thumbs up from @staltz so we have 2 approving reviews

**Comment by staltz** [comment]
(On mobile:) I approve it too! Very good PR

**Comment by shesek** [comment]
Is there a reason this was not implemented for `history.replace`?

**Pull request merged**
