### PR TITLE
fix(http): allow lazy (cancellable) requests

### PR DESCRIPTION
**Pull request by Hypnosphi**
ISSUES CLOSED: #355

Usage: `{url: 'http://example.com', lazy: true}`.

I have no idea how to add tests for request abortion, need help here.

### CODE REVIEW

**Comment by whitecolor** [comment]
@Hypnosphi 
Does it all to make driver request lazy be default?

Maybe should be reverse `eager` option instead of `lazy`, what is more semantically expressive?
@staltz @TylorS

**Comment by Hypnosphi** [comment]
The main idea is that non-breaking changes are generally better than breaking

**Comment by whitecolor** [comment]
@Hypnosphi what breaking change are you talkin about?

**Comment by Hypnosphi** [comment]
Changing default behaviour would break a lot

**Comment by whitecolor** [comment]
I mean not changing default behaviour, but adding a driver option. By default all requests should be eager, but you may set them to be lazy with this option.

An another thing is just a word: `lazy` vs `eager` what is more semantically expressive.

**Comment by staltz** [comment]
Thanks @Hypnosphi this looks good, and I agree for now it's better to introduce a simple non-breaking feature.

**Comment by whitecolor** [comment]
@staltz are you ok with `lazy` name for this param?

And I'm not proposing any breaking change. I said that this param should be also added for the whole driver, but in case of `lazy` param it will be `false` by default, what breaking changes are here?

**Comment by staltz** [comment]
Yeah I think `lazy` is a good name since it works as an opt-in.

**Comment by whitecolor** [comment]
Ok, nice.

**Comment by whitecolor** [comment]
Ok nice. I've used the same param for new version of `cycle-async-driver`, here is docs: https://github.com/whitecolor/cycle-async-driver#lazy-drivers-and-requests

**Comment by whitecolor** [comment]
@staltz what about driver scope `lazy` param (false by default)?

**Comment by staltz** [comment]
Let's discuss that one a bit more, since it's a larger feature. This PR was a very small addition, but fixed the bug for those needing a fix.

**Comment by whitecolor** [comment]
Well it will just assume `lazy: true` for all the requests (as it was in the previous version of HTTP, driver) I see no problems here.

**Comment by whitecolor** [comment]
@staltz though you maybe right, and default laziness may not be is not needed for HTTP driver case.

**Comment by Hypnosphi** [comment]
I think it's doable now, the driver option, given that you always have an opt-out by apparently passing `lazy: false` in the request

**Comment by Hypnosphi** [comment]
Now I think of a bit wider feature: driver accepts an options hash, which will be defaults for all the request. These can even include urlRoot which will be prepended to all the urls

**Comment by staltz** [comment]
Can we discuss this in a new issue?

**Pull request merged**
