### PR TITLE
feat(dom): allow predicate function for preventDefault

### PR DESCRIPTION
**Pull request by jvanbruegge**
ISSUES CLOSED: #65

A follow up for #603 

- [x] I added new tests for the issue I fixed/built
- [x] I ran `make test FOO` for the package FOO I'm modifying
- [x] I used `make commit` instead of `git commit`

### CODE REVIEW

**Comment by jvanbruegge** [comment]
It look like a lot of the tests are run multiple times for the same browser. Is that a timeout issue?

**Comment by jvanbruegge** [comment]
Yes, I also noticed it locally, the tests are restarted quite often

**Comment by staltz** [comment]
@jvanbruegge, thanks.
In this PR, before merging, let's try to get these things right:

- Avoid repeating tricky code
- Avoid closures that may tax performance (e.g. creating `cond` and using that in the stream `map`)

The 3 nested ifs are tricky code, specially with mutation too. I think it would be reasonable to move that code into `fromEvent` and/or EventDelegator. You have the chance of avoiding the map operation if the predicate is applied directly in the xstream Producer (or the xstream "Subject" in the EventDelegator).

**Comment by aronallen** [comment]
Hi,

This is perhaps a separate PR, but I need something very similar for cycle/sandbox. preventDefault: true would work, but we can't pass functions between threads. It could be great if we could pass an object instead, that would compare the values against a set. like 
```
preventDefault: [{button: [0, 1]}] // button is 0 or 1
preventDefault: [{button: [0, 1]}, {keyCode: 13}] // button is 0 or 1 OR keyCode is 13
preventDefault: [{button: [0, 1], keyCode: 13}] // button is 0 or 1 AND keyCode is 13
```

**Comment by jvanbruegge** [comment]
@aronallen You could wrap the DOM driver, taking the object and converting to a function in the main thread. I thinks it's a very specific use case

**Comment by aronallen** [comment]
@jvanbruegge, yes it is very specific. 
The API here is very similar to what I imagined for cycle/sandbox, so it is great to see it is getting official support. We should also consider having this for stopPropagation, and stopImmediatePropagation.
It is quite easy to convert things in the DOM driver, but having this function would prevent WebWorkers from using any Cycle component, if there is a function declared in a sub component, it wouldn't transfer to the main thread.

**Comment by staltz** [comment]
I'm happy this discussion popped up, because so far what we have in `master` in compatible with the use case that Aron describes. The function makes a difference when moving across boundaries. Overall we have to be aware of the format of data, because functions aren't naively serializable in JSON.

Aron, I'm with you that the use case should be supported, but the array API is kind of weird.

**Comment by aronallen** [comment]
@staltz I would also prefer we found a better solution. The array / object thing was just an attempt to describe the condition with data, but I am open to other approaches. The way I thought about the API would be that it accepted one or a set of conditions, and conditions would be a key value pair, of the key, and the possible values, or a single value.

```
preventDefault : { keyCode : 13 } // a very simple use case
preventDefault : { keyCode : 13, shiftKey : false } 
preventDefault : { keyCode : [13, 10] } // prevent default on these keys
preventDefault : [{keyCode : [13, 10]}, { button : [0] }] // either left click, or key is 10 or 13.
```

**Comment by jvanbruegge** [comment]
maybe something like ramda's `path` function:
`preventDefault: { test: ['target', 'dataset', 'someKey'], equals: 'something' }`
`preventDefault: { test: ['target', 'dataset', 'size'], greaterThan: 0 }`
`preventDefault: { test: ['target', 'dataset', 'someKey'], in: ['a', 'b', 'c'] }`

```
preventDefault: { test: ['target', 'dataset', 'index'], all: {
    greaterThan: 0,
    any: {
        lessThan: 100,
        greaterThan: 1000
     }
}}
```
This would map to `ev => ev.target.dataset.index > 0 && (ev.target.dataset.index < 100 || ev.taget.dataset.index > 1000)`

**Comment by jvanbruegge** [comment]
So basicly:
```typescript
interface Comparators {
    equals? : any;
    notEquals? : any;
    greaterThan? : any;
    lessThan? : any;
    greaterOrEqual? : any;
    lessOrEqual? : any;

    in? : any[];

    all? : Comparator;
    any? : Comparator;
}
type PreventDefaultOptions = Comparator & { test: string[] };
```

**Comment by staltz** [comment]
That would work. That said, I'm curious why do we really need conditional preventDefault in the first place? I went back through the discussions and it seems the use case was raised up by `@`abaco just as a "what if?". I think we need to ask ourselves what are the real-world-looking use cases for this feature, and whether it is worth solving, and also how much would it cost, i.e. the impact it has on performance or code size or code complexity.

**Comment by jvanbruegge** [comment]
I dont know, I need only the boolean

**Comment by staltz** [comment]
Okay, I would suggest keeping this PR around, then open an issue about *conditional preventDefault*, label it priority maybe, and go on to solve more important things.

**Comment by jvanbruegge** [comment]
:+1:

**Comment by jvanbruegge** [comment]
Closing this is favor of #610 (without functions) and #611

**Pull request closed without merging**
