### PR TITLE
perf(META): use Google Closure Compiler instead of uglify-js

### PR DESCRIPTION
**Pull request by maximilianmikus**
ISSUES CLOSED: #619

- [ ] I added new tests for the issue I fixed/built
- [X] I ran `make test` for the all the packages
- [X] I used `make commit` instead of `git commit`

### CODE REVIEW

**Comment by maximilianmikus** [comment]
```
run/src/index.ts[1, 1]: This file has 316 lines, which exceeds the maximum of 300 lines allowed. Consider breaking this file up into smaller parts
```
I did not change run/src/index.ts ... From what I can figure, this is the reason the tests failed. Have not found any other error in the travis-ci logs.

**Comment by staltz** [comment]
Don't worry about the unrelated errors. Looks good to merge. Thanks @maximilianmikus !

**Comment by kylecordes** [comment]
@staltz I noticed the change to use Closure Compiler for better minification - great idea! It uses the JS version:

https://github.com/google/closure-compiler-js

which says: "This is an experimental release - meaning some features are not available and performance may not be on-par with the Java implementation."

I've been working with Closure Compiler over in other contexts (Angular, ClojureScript) and can confirm this description is true - the Java version is long-proven and intended for production use, the JS version is experimental in-progress. It might turn out to be sufficient already for Cycle's purpose, but warrants close attention as a member of the "experimental Closure Compiler JS" community, rather than the "using a long proven tool, don't need to pay any attention" community.

**Comment by staltz** [comment]
@kylecordes this should be a rather harmless change because GCC is only used to produce a `dist/foo.min.js` file and these are usually just used for those cases where you directly import this script into your HTML. Usually that's not the case with serious frontend projects. There should be a bundler like Browserify or Webpack and then one of the post-processing steps should be minification. This PR does not affect that use case.

**Pull request merged**
