### PR TITLE
Add mockHTTPDriver helper

### PR DESCRIPTION
**Pull request by Sinewyk**
Here is the rebased and up to date helper to test the HTTP driver.

Does it also need to be tested inside the browser ?

- [x] There exists an issue discussing the need for this PR #567 
- [x] I added new tests for the issue I fixed or built
- [x] I used `pnpm run commit` instead of `git commit`

### CODE REVIEW

**Comment by jvanbruegge** [comment]
No, mockHTTP source is just like mockDOM source intended for node testing

**Comment by Sinewyk** [comment]
Kind of missed the point then. Not sure what the difference is, will check later.

**Comment by Sinewyk** [comment]
Talked about it on gitter, may be correct ?

Tagging @Widdershin because you may be interested.

**Comment by Sinewyk** [comment]
Closing because callbag rewrite, and all these issues _should_ disappear.

**Pull request closed without merging**
