### PR TITLE
feat(http): support SSL certificate authentication

### PR DESCRIPTION
**Pull request by stevenmathews**
- [ ] I added new tests for the issue I fixed/built
- [X] I ran `npm test` for the package I'm modifying
- [X] I used `npm run commit` instead of `git commit`

Tried to add a test but got stuck, so tested manually.

### CODE REVIEW

**Comment by TylorS** [comment]
Hey @stevenmathews thanks for this, any chance you could write a test or two for this?

**Comment by stevenmathews** [comment]
How would you go about writing a test for this? Not really sure how to start.

**Comment by TylorS** [comment]
@staltz You'll have to look at this then, I actually don't know how to test this thing :)

@stevenmathews Thanks again, you got my standard response to things without tests, but like you, I have no idea :smile:

**Comment by staltz** [comment]
One Does Not Simply Write Tests For This.
Thanks @stevenmathews, I'll merge it, it probably helps someone even without tests.

**Pull request merged**
