### PR TITLE
refactor(time): enhanced type definitions for MockTimeSource#diagram

### PR DESCRIPTION
**Pull request by jsamr**
diagram method has now three signatures
- the first with one argument, returning `Stream<number | string>`
- the second with two arguments, with the latest an `Array<T>` of values, returning
`Stream<T>`
- the third with two arguments, with the latest an `ObjectDictionary<T>` of values,
returning `Stream<T>`

I didn't add tests since this addition aims to reinforce an existing contract.

- [x] I ran `make test FOO` for the package FOO I'm modifying
- [x] I used `make commit` instead of `git commit`

### CODE REVIEW

**Comment by Widdershin** [comment]
Hey @sveinburne,

Thanks for this contribution! And for moving your pull request over.

Sorry for my delay in getting back to you.

Would you be able to take a look at the CI failure and see if you can determine the cause?

**Comment by Widdershin** [comment]
Will merge this after the fix for #672 lands.

**Comment by sveinburne** [comment]
Hi @Widdershin, sorry for my late answer ! Was in holiday. Will take a look this week-end, 
cheers

**Comment by Widdershin** [comment]
@sveinburne no worries! 😄 @jvanbruegge and I are still sorting out our approach to #672 so we wouldn't have been able to merge this in any case.

**Comment by sveinburne** [comment]
All right ! That is why I passed the tests locally but not on CI server I guess !

**Pull request closed without merging**
