### PR TITLE
chore(time): upgrade rxjs dependency to 6.2.x

### PR DESCRIPTION
**Pull request by Widdershin**
Targeting the same version as rxjs-run.

### CODE REVIEW

**Comment by staltz** [comment]
Great PR! One thing: could you change `chore(time)` to `fix(time)`? This way the commit will show in the changelog

**Comment by Widdershin** [comment]
@staltz done 😄

**Comment by staltz** [comment]
By the way, what's your opinion about the breaking changes, would the next version be major or minor?

**Comment by Widdershin** [comment]
I'd say just minor for now, @cycle/time is still pre 1.0.

People tend to attach a bit of significance to a 1.0 release so I'd say
let's hold off on that for now.

**Comment by staltz** [comment]
Release 0.14.0

**Pull request merged**
