### PR TITLE
feat(history): update to history v4 WIP

### PR DESCRIPTION
**Pull request by TylorS**
- [x] I added new tests for the issue I fixed/built
- [x] I ran `npm test` for the package I'm modifying
- [x] I used `npm run commit` instead of `git commit`

---

This is still a work in progress.

Simplifies the API for users by tying it more tightly to mjackson/history v4
## Breaking Changes

BEFORE:

``` typescript
// node.js
import { makeHistoryDriver, createServerHistory } from '@cycle/history'

const history = createServerHistory()

Cycle.run(main, {
  history: makeHistoryDriver(history)
})

history.push(req.url)

// browsers

// html5 api
import { makeHistoryDriver } from '@cycle/history'}
import { createHistory } from 'history'

Cycle.run(main, {
  // with the second param being optional - capture by default is FALSE
  history: makeHistoryDriver(createHistory, { capture: true })
})

// hash history

import { makeHistoryDriver } from '@cycle/history'
import { createHashHistory } from 'history'

Cycle.run(main, {
  history: makeHistoryDriver(createHashHistory())
})
```

AFTER:

``` typescript
// node.js
import { createServerHistoryDriver } from '@cycle/history'

Cycle.run(main, {
  history: createServerHistoryDriver({ initialUrls: [ req.url ] })
})

// browsers

// html5
import { makeHistoryDriver } from '@cycle/history'

Cycle.run(main, {
  history: makeHistoryDriver()
})

// with capture = true eqivalent
import { makeHistoryDriver, captureClicks } from '@cycle/history'

Cycle.run(main, {
  history: captureClicks(makeHistoryDriver())
})

// hash history

import { makeHashHistoryDriver } from '@cycle/history'

Cycle.run(main, {
  history: makeHashHistory()
})
```

Should contain significantly better typings, and should be especially better for those users that are using TypeScript.
## Things that still need fixing
- [ ] Fix finicky browser tests
- [x] Provide Stream library specific typings
- [x] Get feedback on API
- [ ] Update README with new API (write inline JSDoc)

### CODE REVIEW

**Comment by staltz** [comment]
@TylorS can you split this single commit into multiple commits? E.g. it's hard to review both API changes and test migrations to TypeScript in the same commit. If the API changed I'm curious about how did the tests change. But if we have first a commit to migrate to TypeScript, and then another commit that changes the API plus changes some parts of the tests, it's possible to see how do the tests change with the API change. But currently with one commit I'd have to compare line by line each test file with my eyes.

**Comment by staltz** [comment]
@TylorS you're so fast. ❤️ 

You might want to rebase this branch with master since I just pushed some stuff there.

**Comment by TylorS** [comment]
@staltz Split this up into smaller commits as requested. But I'm not sure how to show any migration of the tests as I started from scratch with them to use stream adapters to make it much easier to maintain instead of having 3 tests files that are purely duplication (most, xstream, rxjs). Much of the Source code has been placed in new files and split up a bit better where it made sense.

**Comment by TylorS** [comment]
Rebased :)

**Comment by eshansingh** [comment]
@TylorS You, sir, are incredibly fast.

**Comment by staltz** [comment]
SPEED OF LIGHT

**Comment by TylorS** [comment]
I also updated my TODO-list to add the need for stream-library specific typings like @cycle/dom and others currently provide.

**Comment by TylorS** [comment]
And started a list of breaking changes

**Comment by staltz** [comment]
> And started a list of breaking changes

Great

**Comment by staltz** [comment]
About the before/after of the API, I like the improvements 👍. Less low level stuff to care about.

Question: what's the point of importing the capture clicks here?
```js
import { makeHistoryDriver, captureClicks } from '@cycle/history'

Cycle.run(main, {
  history: captureClicks(makeHistoryDriver())
})
```

**Comment by staltz** [comment]
This task "*Update README with new API*" can be done inline with the source code. Just write JSDoc in the index.ts, like we do in Cycle DOM, and then the README.md itself will be autogenerated.

**Comment by staltz** [comment]
@TylorS could you git rebase -i the commit `feat(history): update and simplify api` to reword it?
The message itself has some broken parts. And because this was the breaking change, it will pop up in the changelog, we could write a bit more "for humans" about how to upgrade.

```
 feat(history): update and simplify api

                                                                                                                                           # Please enter the commit message for your changes. Lines starting
Make hard dependency on mjackson's history library to simplify the API users are asked to use.  # with '#' will be ignored, and an
empty message aborts the commit.
                                                                                                                                           # On branch tylors/feat/history-rework
BREAKING CHANGE:
makeHistoryDriver(history: History, options?: HistoryOptions) ->  makeHistoryDriver(options?: BrowserHistoryOptions)
new API - makeServerHistoryDriver (options?: MemoryHistoryOptions)
new API -  makeHashHistoryDriver(options?: HashHistoryOptions)
captureClicks is now provided as a Higher Order Driver  \\`captureClicks(makeHistoryDriver())\\`
                                                                                                                                           #	modified: history/src/index.ts
ISSUES CLOSED: 434 465
```

E.g. something like
```
feat(history): update and simplify api

Make hard dependency on mjackson's history library to simplify the API users are asked to use.

BREAKING CHANGE:
![yes](https://img.shields.io/badge/will%20it%20affect%20me%3F-yes-red.svg)
We updated the underlying history library from v3 to v4. The API for this driver changed, you no longer need to provide the low-level history object to the driver. Just choose your desired history driver, e.g. makeServerHistoryDriver() or makeHistoryDriver() or makeHashHistoryDriver() which may accept an optional options object.
makeHistoryDriver(history: History, options?: HistoryOptions) ->  makeHistoryDriver(options?: BrowserHistoryOptions)
new API - makeServerHistoryDriver (options?: MemoryHistoryOptions)
new API - makeHashHistoryDriver(options?: HashHistoryOptions)
captureClicks is now provided as a Higher Order Driver: captureClicks(makeHistoryDriver())

ISSUES CLOSED: #434 #465
```

**Comment by staltz** [comment]
I reviewed the PR. Looks good (thanks for splitting in smaller commits, made it much easier to review). So I'd say we can tick this box:

- Get feedback on API

For this:

- Fix finicky browser tests

You could try turning on testem tests in npm script `test-ci`, and running it again in Travis. Lately SauceLabs have been behaving.

**Comment by staltz** [comment]
Was merged into `unified` branch.

**Pull request closed without merging**
