### PR TITLE
WIP: remove polyfills

### PR DESCRIPTION
**Pull request by jvanbruegge**
ISSUES FIXES: #700 
Here is a list of removed polyfills (as a note to myself):
- Element.matches
- ES6 Map

- [x] There exists an issue discussing the need for this PR
- [ ] I added new tests for the issue I fixed or built
- [ ] I ran `make test FOO` for the package FOO I'm modifying
- [ ] I used `make commit` instead of `git commit`

### CODE REVIEW

**Comment by jvanbruegge** [comment]
lol, somehow does removing the packages increase the bundle size.
Before this commit: 554.3KB stat, 161.22KB parsed, 46.47KB gzip
After this commit: 679.8KB stat, 207.3KB parsed, 60.34KB gzip

**Comment by jvanbruegge** [comment]
Found the problem:
```diff
-import {classNameFromVNode} from 'snabbdom-selector/lib/commonjs/classNameFromVNode';
-import {selectorParser} from 'snabbdom-selector/lib/commonjs/selectorParser';
+import {classNameFromVNode, selectorParser} from 'snabbdom-selector';
```
With that change reverted:
- With scope hoisting: 513.69KB stat, 146.56KB parsed, 42.45KB gzip
- Without scope hoisting 513.56KB stat, 162.83KB parsed, 46.35KB gzip

**Comment by jvanbruegge** [comment]
Of course there is no tree shaking because of @atomrc 's PR (https://github.com/TylorS/snabbdom-selector/pull/19)

**Comment by jvanbruegge** [comment]
tree

**Comment by jvanbruegge** [comment]
tree2

After the removal of `es6-map` you can see the main problem: all the testing dependencies of `@cycle/time` are pulled in

**Comment by jvanbruegge** [comment]
The import of the testing related stuff looks like this issue: https://github.com/webpack/webpack/issues/5654

**Comment by Frikki** [comment]
> Of course there is no tree shaking because of @atomrc 's PR (TylorS/snabbdom-selector#19)

I've forwarded the message to Tylor. Perhaps you should open an issue with a request for a revert.

**Comment by jvanbruegge** [comment]
@Frikki did two PRs to solve the problem once and for all

**Comment by staltz** [comment]
@jvanbruegge what did you use to generate those diagrams? :)

**Comment by jvanbruegge** [comment]
webpack stats plugin and the bundle analyse webapp

**Comment by jvanbruegge** [comment]
Is now done in #759

**Pull request closed without merging**
