### PR TITLE
docs(devtool): use correct package name in devtool docs

### PR DESCRIPTION
**Pull request by maximilianmikus**
ISSUES CLOSED: #623

- [ ] I added new tests for the issue I fixed/built
- [ ] I ran `make test FOO` for the package FOO I'm modifying
- [X] I used `make commit` instead of `git commit`

### CODE REVIEW

**Comment by staltz** [comment]
Hi @maximilianmikus 
Thanks for submitting this PR. Before merging it, could you notice that we also need these changes in `devtool/src/panel/view`?

**Comment by maximilianmikus** [comment]
Hi @staltz, thank you for the hint, added the change :)

**Comment by maximilianmikus** [comment]
`historyDriver - xstream should allow going back/forwards with `go`, `goBack`, `goForward` FAILED`

seems I don't have much luck with the tests :)

**Comment by staltz** [comment]
Thanks @maximilianmikus. Those CI tests are unrelated (SauceLabs is usually failing).

**Pull request merged**
