### PR TITLE
[history] Update `history` to v5

### PR DESCRIPTION
**Pull request by ryota-ka**
- [ ] There exists an issue discussing the need for this PR
- [ ] I added new tests for the issue I fixed or built
- [x] I used `pnpm run commit` instead of `git commit`

### CODE REVIEW

**Comment by staltz** [comment]
The code changes look great, we just need to check whether the tests pass before merging.

**Comment by ryota-ka** [comment]
Hmm, why won't the build job be kicked? 🤔

**Comment by staltz** [comment]
It's based on Travis, and lately Travis has disappeared, I don't know what happened to their business. I have the same problem in many repos.

**Comment by staltz** [comment]
I noticed that the tests don't pass but it's a systemic problem since we've moved to building the code to `cjs` and `es6` and now Karma and ts-node are not adjusted for those new paths. I was stuck with your PR because I tried to restore the tests for all of these packages, and I think that's going to be wasted work since the Neo Cycle branch (e.g. #969) is progressing.

So I'll just merge your PR (thank you for your patience) and make a new version since I believe that this will be useful for you and the code looks correct.

**Comment by staltz** [comment]
`@cycle/history@9.0.0`

**Pull request merged**
