### PR TITLE
fix errors in CI

### PR DESCRIPTION
**Pull request by jvanbruegge**
Let's hope this is green again now

- [ ] There exists an issue discussing the need for this PR
- [ ] I added new tests for the issue I fixed or built
- [x] I used `pnpm run commit` instead of `git commit`

### CODE REVIEW

**Comment by jvanbruegge** [comment]
The `sed` line in the travis yaml is to hotfix https://github.com/snabbdom/snabbdom/pull/460 for now in CI, just to test it

**Comment by jvanbruegge** [comment]
nice, it works. Still a few flaky tests, but at least no test that fails always. Now we have to wait for snabbdom to merge the fix

**Comment by staltz** [comment]
Awesome! Let's wait for the snabbdom merge then :)

**Comment by jvanbruegge** [comment]
@staltz this can be merged now, snabbdom was finally updated

**Comment by jvanbruegge** [comment]
Wait, no, HTTP is making problems now, will check on that later

**Comment by staltz** [comment]
So close to getting this merged!

**Pull request merged**
