### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Gastonite**
just a missing "p"

### CODE REVIEW

**Comment by jvanbruegge** [comment]
Simple fix, thank you

**Comment by staltz** [comment]
I know this is a nitpick, but we should have rebased/merged this with a rename of the commit message to follow the commit message convention, it's important for changelog generation.

**Comment by jvanbruegge** [comment]
I did, check the commits on the master branch

**Comment by staltz** [comment]
Good! Thanks!

**Pull request merged**
