### PR TITLE
#480 - added doc for hello-world

### PR DESCRIPTION
**Pull request by gurrrung**
- [x] There exists an issue discussing the need for this PR
- [ ] I added new tests for the issue I fixed or built
- [x] I used `pnpm run commit` instead of `git commit`

### CODE REVIEW

**Comment by staltz** [comment]
Hi :)
Thanks for submitting this PR, we appreciate any kind of desire to help. Before we can merge this, notice that documentation that paraphrases the code line by line is not as helpful as documentation that explains the big picture approach and motivation. I think the last sentences you added were better than the first sentences. And also note that we actually need this step to be done:

> - [ ] I used pnpm run commit instead of git commit

**Comment by gurungrahul2** [comment]
@staltz sorry, I didn't catch about `pnpm run commit` first but now i will git reset and do a --hard push with that, and should I make changes to the initial lines or they are alright for now ?

**Comment by gurungrahul2** [comment]
@staltz PTAL, I pushed new changes.

**Comment by gurungrahul2** [comment]
@stalz review ping.

**Comment by gurungrahul2** [comment]
@stalz

**Comment by gurungrahul2** [comment]
@staltz

**Pull request closed without merging**
