### PR TITLE
Conditional predicate, a continuation of PR #615

### PR DESCRIPTION
**Pull request by staltz**
This is just a rebase + continuation of PR #615, deployed to a different branch because #615 was in Jan's own repo.

### CODE REVIEW

**Comment by jvanbruegge** [comment]
The last PR that was made before joining the core team :D

**Comment by staltz** [comment]
Thanks for the approval. I'm still going to tweak a commit message a bit just to make it better for the changelog.

**Comment by jvanbruegge** [comment]
approved

**Comment by staltz** [comment]
Merged. Thanks @jvanbruegge !

**Pull request merged**
