### PR TITLE
fix(dom): place eventHandler on all elements for nonBubbling events

### PR DESCRIPTION
**Pull request by ntilwalli**
Original code only selected first element for place nonBubbling event handlers, this update applies event handlers for all elements associated with selector.  I also consolidated around fixed some inconsistencies like including 'assert' dep and using typescript v3.2.4 which allows all tests to pass.

ISSUES CLOSED: #893

- [x] There exists an issue discussing the need for this PR
- [ ] I added new tests for the issue I fixed or built
- [x] I used `pnpm run commit` instead of `git commit`

### CODE REVIEW

**Comment by ntilwalli** [comment]
Dunno why it failed... passed for me locally

**Comment by ntilwalli** [comment]
Mistakenly closed

**Comment by staltz** [comment]
@ntilwalli Thanks for finding this and fixing it! My only concerns are meta-issues, otherwise I'm glad to merge this fix. First we got to get the CI green on master branch (it fails not just for your PR), and then we need some changes to this PR:

- There should be a `chore` commit that only updates TypeScript for all packages
- There should be a `fix(dom)` commit dedicated to updating snabbdom
- There should be a `fix(dom)` commit dedicated to fixing #894 and nothing else
- Tests for #894 would be good to have
  - It's not absolutely necessary though. Writing a test for this seems rather easy, the only difficult part is figuring out how to simulate `mouseover`. Maybe there is another non-bubbling event that we can trigger

**Comment by ntilwalli** [comment]
@staltz I can split up the commits, but a few questions...

* Will you look into the CI issues after I split the commits?
* I actually downgraded Typescript from 3.5 to 3.2 on `master` and `master/dom` to get the `dom` tests to pass.  Should I apply that change for all packages?  Upgrading and the requisite typing fixes seems like a lot of work.  I'm not conversant with Typescript typings, I'm an `any`-addict
* I also added an assert-package `devDependency`, should that be it's own commit or can that be rolled in with the snabbdom fix?

**Comment by ntilwalli** [comment]
Commit broken into three different PRs, `typescript`, `deps` and `nonBubblingFix`

**Pull request closed without merging**
