### PR TITLE
Update rxjs-run to use rxjs6

### PR DESCRIPTION
**Pull request by theJian**
This PR update rxjs-run to be able to use rxjs6.

- [x] There exists an issue discussing the need for this PR
- [ ] ~~I added new tests for the issue I fixed or built~~
- [x] I used `make commit` instead of `git commit`
- [x] Fix tests

### CODE REVIEW

**Comment by staltz** [comment]
Thanks for the initiative!

**Comment by theJian** [comment]
It's ready for review. Besides the code changes, some dependencies were updated. Not necessary maybe, but doesn't hurt anyone I think.

**Comment by staltz** [comment]
Looks good to me! @jvanbruegge ?

**Comment by jvanbruegge** [comment]
Yes, looks good, you can merge it

**Pull request merged**
