### PR TITLE
chore(META): fix makefile on linux to fix build

### PR DESCRIPTION
**Pull request by Widdershin**
Add new scripts to run tests for all packages

ISSUES CLOSED: #584

Let's see if this works. In the longer term we should probably find a fully cross platform solution but hopefully this will support OSX and Linux.

### CODE REVIEW

**Comment by Widdershin** [comment]
Okay, got this passing, and I also verified that it fails.

Had to change the Makefile a bit to get it to report failures, turned out using `;` to chain commands was dropping the exit codes. It pretty much boils down to the difference between `false; true` and `false && true`.

I also changed it to run the tests before linting so that a lint error won't prevent the tests from running. The rationale here is that tests are more important than lint errors, so we should address test failures first and style issues second. (Ideally a contributor will run local tests anyway so this should not be very consequential).

@staltz this is ready to go, pending your review.

**Comment by staltz** [comment]
Looks good! Let's wait for Travis, and I'll also run this on my mac and see that it all works

**Comment by staltz** [comment]
Works on mac :+1:.

**Comment by Widdershin** [comment]
Failure was sauce labs timing out, serves as a useful demonstration that it reports failures 😄

**Comment by staltz** [comment]
Red is the new green.

**Pull request merged**
