### PR TITLE
Add ES6 module builds

### LINKED ISSUE #660: @cycle/time: cjs bundle means lodash deps for mocking are pulled in on production apps
**Code to reproduce the issue:**
mock-time-source.ts uses package combine-errors, which uses package lodash.uniqby which then pulls in a bunch of extra lodash stuff which bloats the bundle considerably if you're not already using lodash.

lodash.uniqby brings in lodash.iteratee (56kb) among others - all in all it adds up to almost 100kb of extra code that won't be used:
extralodashdeps

This wouldn't be a problem if we were able to use ES module versions of the packages (rather than bundled cjs) and a treeshaking/dead code eliminating bundler as in theory it could remove the unused modules.

My solution is to split the mock vs non-mock timesource files so in your tests you can pull in the mock time source (including any dependencies needed, e.g. lodash) but your app can pull in the skinnier time driver alone.
Here's an example:
https://github.com/cyclejs/time/compare/master...willheslam:separate-test-deps?expand=1

**Expected behavior:**
No lodash deps in production bundle that does not use mock sources

**Actual behavior:**
lodash.iteratee and other deps are included even  when not using mock sources

**Versions of packages used:**
cycle/time: ^0.8.0

### LINKED ISSUE #661: Provide ES6 bundles
You can specify a `module` entry in `package.json` that is used to provide ES6 modules besides commonjs. (More info [here](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c)).

I would like to tackle that.
Will resolve #660

### PR DESCRIPTION
**Pull request by jvanbruegge**
fixes #661 
fixes #660

### CODE REVIEW

**Comment by jvanbruegge** [comment]
@staltz Should be ready to merge

**Comment by staltz** [comment]
@jvanbruegge Good catch! Looks good to merge, except for the commit messages. I could do a squash if you don't mind. Then, we'll have to `make release-minor` for each package in order to get pkg.module making some difference.

**Comment by jvanbruegge** [comment]
Yeah, sqash them :)

**Comment by jvanbruegge** [comment]
I sqashed it myself.
Yeah, a new release for everything would be needed

**Comment by staltz** [comment]
All packages got new minor versions 👍

**Comment by jvanbruegge** [comment]
:+1:

**Comment by 5310** [comment]
I noticed that two of the source files under `@cycle/dom` use `require()`s to polyfill ES6 maps. Unfortunately, these are retained in the ES6 builds:
- https://github.com/cyclejs/cyclejs/blob/master/dom/src/IsolateModule.ts#L3
- https://github.com/cyclejs/cyclejs/blob/master/dom/src/makeDOMDriver.ts#L14

These break the library under Rollup (using `rollup-plugin-node-resolve` and bundling to ES6 modules themselves) when the ES6 build is imported as is and the browser throws an exception when encountering the unexpected `require()`s. 

Changing these require statements to `import MapPolyfill from 'es6-map'` seems to work out just fine. If this is an acceptable change, should I submit this as a PR?

**Comment by jvanbruegge** [comment]
Yeah, do it

**Comment by 5310** [comment]
Should I leave the `es6-map` module type-less or at least add in a `declare module 'es6-map';` definition file? This still raises untyped function calls warnings, but I'm afraid I'll need help with providing proper definitions as I don't know much about TypeScript.

**Comment by jvanbruegge** [comment]
Leave it like that, that's just a Shim for the ES6 map which definition is included in Typescript itself

**Pull request merged**
