### PR TITLE
fix(history): update history to v4.7.x

### PR DESCRIPTION
**Pull request by jvanbruegge**
ISSUES CLOSED: #702

- [x] There exists an issue discussing the need for this PR
- [ ] I added new tests for the issue I fixed or built
- [x] I ran `make test FOO` for the package FOO I'm modifying
- [x] I used `make commit` instead of `git commit`

### CODE REVIEW

**Comment by staltz** [comment]
I'll squash and reword the commit to say `update history to v4.7.x`

**Comment by staltz** [comment]
Actually, besides the commit message, check also the Travis build that errored with:

```
[1/4] Resolving packages...

Couldn't find any versions for "@types/history" that matches "4.7.x"

? Please choose a version of "@types/history" from this list: (Use arrow keys)

❯ 3.2.2 

  2.0.49 

  4.6.0 

  4.5.2 

  4.5.1 

  2.0.48 

  3.2.1 
```

**Comment by jvanbruegge** [comment]
Oh, yeah, that was a mistake

**Comment by jvanbruegge** [comment]
@staltz can you merge this? then you can also publish a new version

**Comment by staltz** [comment]
Thanks Jan

**Pull request merged**
