### PR TITLE
Add LICENSE file to all packages

### PR DESCRIPTION
**Pull request by jvanbruegge**
Technically we are required to include a full copy of the license with all distributions, so with this the npm packages also ship with a license file.
I also replaced the copyright owners with "Cycle.js Core Team" as all members and previous members are listed in the `CORE_TEAM.md` file

### CODE REVIEW

**Comment by staltz** [comment]
Oh, I thought we had done that. Good catch, obvious merge.

**Comment by staltz** [comment]
Travis failing should have absolutely nothing to do with this PR.

**Comment by jvanbruegge** [comment]
We would also have to release patch versions of all the packages, so the license is included

**Comment by staltz** [comment]
I can do that

**Comment by jvanbruegge** [comment]
cool, thank you

**Pull request merged**
