### PR TITLE
Enable to handle binary response

### PR DESCRIPTION
**Pull request by maskinoshita**
Add feature to handle binary response to cycle/http.

- [x] I added new tests for the issue I fixed/built
- [x] I ran `make test http` for the package http I'm modifying
- [x] I used `make commit` instead of `git commit`

### CODE REVIEW

**Comment by staltz** [comment]
Good PR. Thanks @maskinoshita !

**Comment by whitecolor** [comment]
Shouldn't this option be called [`responseType`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType)  not just `binary`?

**Comment by staltz** [comment]
Good point @whitecolor. Because we haven't yet released this PR as a new version, this is still possible to change without a breaking change version. I think I agree with you, but I'll leave this up for discussion for a while.

**Comment by maskinoshita** [comment]
I had not considered a useful naming.
I agree with you, @whitecolor. Thanks.

**Comment by staltz** [comment]
We got 3 people agreeing on the name `responseType`. I'll do the rename and release a new version.

**Pull request merged**
