### PR TITLE
Add support for importing <details> and <summary> from @cycle/dom

### PR DESCRIPTION
**Pull request by brookback**
- [ ] There exists an issue discussing the need for this PR. *Trivial change, no real need for issue?*
- [ ] I added new tests for the issue I fixed or built. *No existing tests for this feature.*
- [x] I used `make commit` instead of `git commit`

### CODE REVIEW

**Comment by brookback** [comment]
@jvanbruegge Thanks, done ✨

**Comment by jvanbruegge** [comment]
LGTM, have to wait for @staltz as he has to release the new version anyways

**Comment by staltz** [comment]
Thanks!

**Comment by brookback** [comment]
@staltz Btw, looks like GitHub parsed the `details` tag in the Cycle/DOM [changelog](https://github.com/cyclejs/cyclejs/blob/master/dom/CHANGELOG.md):

skarmavbild 2018-05-02 kl 08 41 08

**Comment by staltz** [comment]
Fixed

**Pull request merged**
