### PR TITLE
fix(dom): add better typings for the hyperscript helpers

### PR DESCRIPTION
**Pull request by jvanbruegge**
- [ ] There exists an issue discussing the need for this PR
- [ ] I added new tests for the issue I fixed or built
- [x] I used `pnpm run commit` instead of `git commit`

### CODE REVIEW

**Comment by jvanbruegge** [comment]
These bad typings are the reason why [the zombie transposition](https://github.com/cyclejs/cyclejs/commit/aff1c9dc46603a2e0935dda4b5aa7aaa943fde7f) could survive for so long in the tests

**Comment by staltz** [comment]
Looks good. I have just one question about this: is it a breaking change? Technically because people had `any` types before, with this change, their TypeScript compiler might light up with many errors.

**Comment by jvanbruegge** [comment]
It should not be as all valid uses of the hyperscript helpers are captured in the types. So if this now throws an error where it did not before, then because of a misuse of the API (like transposition).

**Comment by jvanbruegge** [comment]
one nice thing to do would be to merge https://github.com/snabbdom/snabbdom/pull/325 first, to remove the `any` in the typings

**Comment by jvanbruegge** [comment]
@staltz the snabbdom PR may take ages to be released, let's merge and release this now with any, we can still improve the typings in the future

**Comment by staltz** [comment]
Okay, how about CI?

**Comment by jvanbruegge** [comment]
Should be fixed now

**Comment by jvanbruegge** [comment]
yes, CI is green

**Comment by staltz** [comment]
Can you merge? I'm on mobile

**Pull request merged**
