### PR TITLE
fix(dom): wait for snabbdom's post hooks to clean vnodes (#667)

### PR DESCRIPTION
**Pull request by atomrc**
Initially, vnodes were cleaned (EventListener destroyed) during the snabbdom's \`remove\` or \`destroy\`
hook. Thus, if the vnode is, in fact, used latter on in the DOM, those listeners are now gone.

This patch only removes those nodes at the end of snabbdom's process. Thus if the nodes are needed
latter on, they won't be destroyed

ISSUES CLOSED: #667

- [x] I added new tests for the issue I fixed/built
- [x] I ran `make test FOO` for the package FOO I'm modifying
- [x] I used `make commit` instead of `git commit`

### CODE REVIEW

**Comment by atomrc** [comment]
side note: created a `pack` and tested it against my actual project, I can confirm it fixes #667 :)

**Comment by Widdershin** [comment]
@atomrc sorry for the lack of update. I'll try to find some time to look at this on the weekend. Been moving house recently so hard to find time to focus.

**Comment by staltz** [comment]
Good PR! Thanks a lot @atomrc !

**Comment by atomrc** [comment]
My pleasure. Thanks for the review!

Any idea when could be the next release of @cycle/dom?

**Pull request merged**
