### PR TITLE
Examples sorted, packages updated, annotated/formatted (heavily), reworked (slightly)

### PR DESCRIPTION
**Pull request by dmitriz**
As the title says, all examples are sorted into 3 groups: basic, intermediate, advanced. 
That way a beginner can quickly see which to look up first.
Several had outdated packages, now updated and tested.

Annotated and formatted heavily (and sometimes over-zealously) but any critics welcome.

Few small functions added or removed here and there.

Live `budo` server added to most non-typescript examples. 
I find it handy to play with examples, inspect streams in console and see immediate updates.

- [ ] I added new tests for the issue I fixed/built
(Not really needed as only examples are modified)

- [x ] I ran `npm test` for the package I'm modifying
(Tests pass but I understand that no tests touch the examples)

- [ ] I used `npm run commit` instead of `git commit`
(Just realised that no, sorry.)

### CODE REVIEW

**Comment by staltz** [comment]
Hi :)
Thanks for submitting this PR, we appreciate any kind of desire to help. The beginner/intermediate/advanced classification is really good. Before merging this PR I need you to notice that the annotation and reformatting came to me as a surprise. While it's very useful for a developer to go through all the code and reformat it (it helps to learn the code), it's a personal experience. Maybe the next developer comes and submits another PR to reformat in another way.

I'd like to keep a consistent coding style everywhere in Cycle.js examples, and this includes the cycle.js.org page too. So I need to ask you to revert all the formatting/annotation/refactor changes. Keep the package.json updates and the folder classifications.

Thanks

**Comment by dmitriz** [comment]
Ok, I'll try to go one-by-one. ;)
But the in-browser tests seem to fail, so I don't know how to proceed:

```sh
> @cycle/history@4.1.0 test-browser /Users/zaitsev/Repos/cyclejs/history
> ../node_modules/.bin/testem ci -l Chrome,Firefox

not ok 1 Browser "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome --user-data-dir=/var/folders/vt/6y645drx4m3f7tjn2f4rj2lr0000gn/T/testem-7145 --no-default-browser-check --no-first-run --ignore-certificate-errors --test-type --disable-renderer-backgrounding --disable-background-timer-throttling http://localhost:8080/7145" failed to connect. testem.js not loaded?
```

**Comment by staltz** [comment]
You don't need to test `@cycle/history` if you are just updating the examples.

**Comment by dmitriz** [comment]
True, I was just trying to follow the contributing instructions...
Still would like to understand why all the test failures, if it is problem on my part...

**Comment by brucou** [comment]
what is the status on that?

**Pull request closed without merging**
