### PR TITLE
feat(dom): add preventDefault option

### PR DESCRIPTION
**Pull request by jvanbruegge**
This would remove impure `preventDefault` calls inside the app. Usage:
```javascript
const event$ = sources.DOM.select('.myform').events('submit', { preventDefault: true });

//currently
const event$ = sources.DOM.select('.myform').events('submit')
    .map(ev => {
        ev.preventDefault();
        return ev;
    });
```

- [x] I added new tests for the issue I fixed/built
- [x] I ran `make test FOO` for the package FOO I'm modifying
- [x] I used `make commit` instead of `git commit`

### CODE REVIEW

**Comment by staltz** [comment]
Hey Jan :)
Thanks for submitting this PR. Before merging it, though, I noticed that it's the simplest solution, it is likely we would refactor it later on (for instance, I can see how we would put the preventDefault call inside the EventDelegator or the fromEvent producer), for performance or for less use of tricky mutation. In that future scenario where this refactor happens, it would be important to make sure that the code still works as desired. So we need tests for this one. Usually I'm not strict on asking for tests for everything, but I think this is one of those cases where we need it. The code inside MainDOMSource.events() is very tricky and likely to be refactored.

**Comment by jvanbruegge** [comment]
How would I test this?

**Comment by Widdershin** [comment]
You could check that `event.defaultPrevented` is true when`preventDefault` is true and false otherwise.

https://developer.mozilla.org/en-US/docs/Web/API/Event/defaultPrevented

**Comment by jvanbruegge** [comment]
The CI fails because it was not able to start the iOS browser, the new tests works as expected

**Comment by jvanbruegge** [comment]
Triggering a new build worked :)

**Comment by staltz** [comment]
Great, thanks for the PR @jvanbruegge !

**Comment by aronallen** [comment]
This is perfect for cycle/sandbox :)

**Pull request merged**
