### PR TITLE
Onionify collection

### PR DESCRIPTION
**Pull request by enj0ey**
- [ ] There exists an issue discussing the need for this PR
- [ ] I added new tests for the issue I fixed or built
- [ ] I ran `make test FOO` for the package FOO I'm modifying
- [ ] I used `make commit` instead of `git commit`
- [ ] any minor changes

### CODE REVIEW

**Comment by enj0ey** [comment]
just learning

**Comment by jvanbruegge** [comment]
You do not have any commits by yourself on this branch

**Comment by jvanbruegge** [comment]
@staltz This is also Spam for Hacktoberfest, also wrote an email to prevent @enj0ey to get a tshirt for wasting the time of many maintainers

**Comment by staltz** [comment]
That's a shame. :/
On the other hand, I forgot to merge that branch, it shouldn't be deleted.

**Pull request closed without merging**
