### PR TITLE
fix(dom): add uponStart and uponStop operators for nonBubbling event streams

### PR DESCRIPTION
**Pull request by ntilwalli**
ISSUES CLOSED: 893

- [x] There exists an issue discussing the need for this PR
- [ ] I added new tests for the issue I fixed or built
- [x] I used `pnpm run commit` instead of `git commit`

### CODE REVIEW

**Comment by jvanbruegge** [comment]
Can you rebase on the current master? We fixed the CI problem

**Comment by ntilwalli** [comment]
@jvanbruegge The `Array.from` issue (which causes the failure) on IE11 seems widespread, I see lots of issues on other GH repos that refer to this... Should a polyfill be added?  If so which one?  `core-js`? `array-from-polyfill` also exists...

**Comment by jvanbruegge** [comment]
I had a quick look at your code, and `Array.from` and `Array.find` (both not available in older browsers) are only used in one place, could you maybe rewrite this to avoid this?
Also what is the difference between `UponStart`, `UponEnd` and a simple `delay`?

**Comment by ntilwalli** [comment]
> I had a quick look at your code, and `Array.from` and `Array.find` (both not available in older browsers) are only used in one place, could you maybe rewrite this to avoid this?

Done

> Also what is the difference between `UponStart`, `UponEnd` and a simple `delay`?
 
The upon operators are not like `delay`.  `uponEnd` is the equivalent of `finally` in RxJS and `uponStart` is the equivalent of what would be an `initially` operator in RxJS (which does not currently exist).  They allow imperative code to be run bases on the start/end lifecycle events associated with the stream.  Those operators probably belong in `xstream/extras` but I don't have time to do that PR...

**Comment by ntilwalli** [comment]
@jvanbruegge the failures in the latest push are not associated with the updates I made to the DOM driver.  Seems like a `Map` polyfill is needed for ie10.  Do you want me to add that?

**Comment by ntilwalli** [comment]
@jvanbruegge also I see this error:
```
> @cycle/http@15.1.0 start-test-support-server /home/travis/build/cyclejs/cyclejs/http
> PORT=8070 ts-node test/support/run-server.ts &
Error: listen EADDRINUSE: address already in use :::8070
    at Server.setupListenHandle [as _listen2] (net.js:1279:14)
    at listenInCluster (net.js:1327:12)
    at Server.listen (net.js:1414:7)
    at Function.listen (/home/travis/build/cyclejs/cyclejs/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/application.js:618:24)
    at Object.startServer (/home/travis/build/cyclejs/cyclejs/http/test/support/server.ts:76:7)
    at Object.<anonymous> (/home/travis/build/cyclejs/cyclejs/http/test/support/run-server.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module.m._compile (/home/travis/build/cyclejs/cyclejs/node_modules/.registry.npmjs.org/ts-node/7.0.1/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.require.extensions.(anonymous function) [as .ts] 
```

**Comment by jvanbruegge** [comment]
> Seems like a Map polyfill is needed for ie10. Do you want me to add that?

If you look [here](https://github.com/cyclejs/cyclejs/blob/master/dom/test/browser/setup.ts) there should already be one

**Comment by jvanbruegge** [comment]
Oh, just checked the logs, the http driver needs the map. Ok, can you add it similar to the DOM driver?

**Comment by jvanbruegge** [comment]
> also I see this error:

**Comment by jvanbruegge** [comment]
> Oh, just checked the logs, the http driver needs the map. Ok, can you add it similar to the DOM driver?

I wonder where this usage of `Map` is, the HTTP driver does not need maps AFAIK :thinking:

**Comment by ntilwalli** [comment]
The `Map` error seems to be lower-level than the tests, having to do with the browserstack environment... I grepped for the `Map` string

> > also I see this error:
> 
> Maybe change in the package.json this:
> 
> ```
> "start-test-support-server": "PORT=8070 ts-node test/support/run-server.ts &",
> ```
> 
> to
> 
> ```
> "start-test-support-server": "(PORT=8070 ts-node test/support/run-server.ts || true) &",
> ```

This fix did not work.  I see the EADDRINUSE error locally as well.

**Comment by ntilwalli** [comment]
> > Oh, just checked the logs, the http driver needs the map. Ok, can you add it similar to the DOM driver?
> 
> I wonder where this usage of `Map` is, the HTTP driver does not need maps AFAIK 🤔

I couldn't find it either when I grepped but seems to be lower level in the Karma bundle... dunno, I can add the polyfill assuming the EADDRINUSE issue can be addressed.  Right now the HTTP tests don't pass locally because of that...

**Comment by jvanbruegge** [comment]
You would see EADDRINUSE when you still have a test server running. Locally just kill it, in CI this does not matter

**Comment by ntilwalli** [comment]
@jvanbruegge the EADDRINUSE issue is actually a symptom of a failure in running `karma`.  The exception happens theres so the process cleanups (kill calls) never happen

The logs show this exception which I don't get:
```
10 silly lifecycle @cycle/http@15.1.0~test-browser: Args: [ '-c',
10 silly lifecycle   'pnpm run start-test-support-server && karma start && pnpm run stop-test-support-server' ]
11 silly lifecycle @cycle/http@15.1.0~test-browser: Returned: code: 1  signal: null
12 info lifecycle @cycle/http@15.1.0~test-browser: Failed to exec test-browser script
13 verbose stack Error: @cycle/http@15.1.0 test-browser: `pnpm run start-test-support-server && karma start && pnpm run stop-test-support-server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:188:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:188:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

**Comment by jvanbruegge** [comment]
ah, yes, it should probably be `start-support-server && (karma start ; stop-support-server)`

**Comment by jvanbruegge** [comment]
but then the exit code is not correct :thinking:

**Comment by jvanbruegge** [comment]
`start-support server && (karma start; code=$?; stop-support-server; exit $code)` should work

**Comment by ntilwalli** [comment]
Didn't work.

```
10 silly lifecycle @cycle/http@15.1.0~test-browser: Args: [ '-c',
10 silly lifecycle   'pnpm run start-test-support-server && (karma start; code=$?; pnpm run stop-test-support-server; exit $code)' ]
11 silly lifecycle @cycle/http@15.1.0~test-browser: Returned: code: 1  signal: null
12 info lifecycle @cycle/http@15.1.0~test-browser: Failed to exec test-browser script
13 verbose stack Error: @cycle/http@15.1.0 test-browser: `pnpm run start-test-support-server && (karma start; code=$?; pnpm run stop-test-support-server; exit $code)`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:188:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:188:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

**Comment by jvanbruegge** [comment]
Sorry that this take so long, I was really busy with my thesis. I haven't had the chance to look at the actual logic a bit more closely, but `uponStart` and `uponEnd` are not needed. This works (tried locally):
```ts
const self = this;
let subscription: any = null;
return xs.create({
  start: listener => {
    self.nonBubblingListenersToAdd.add(input);
    self.setupNonBubblingListener(input);
    subscription = nonBubbleSubject.subscribe(listener);
  },
  stop: () => {
    const [_s, et, ef, _d] = input;
    const elements = ef.call();

    elements.forEach(function(element: any) {
      const subs = element.subs;
      if (subs && subs[et]) {
        subs[et].unsubscribe();
        delete subs[et];
      }
    });

    self.nonBubblingListenersToAdd.delete(input as any);

    subscription.unsubscribe();
  },
});
```
Also the `shrinkwarp` should not be generated (maybe your pnpm version is a bit old?)

**Comment by staltz** [comment]
Yes, the new operators are not needed to solve this DOM driver issue, but @ntilwalli I encourage you to publish uponStart and uponEnd as operators in their own libraries. I think they would actually be really useful, and the best place for an operator is a library, not the DOM driver code. E.g. I've made `xstream-sample`.

**Comment by ntilwalli** [comment]
Finally got around to this.  `uponStart` and `uponEnd` operators are no longer used.  

I've also created npm packages for those operators: 
https://www.npmjs.com/package/xstream-upon-start
https://www.npmjs.com/package/xstream-upon-stop

Additionally, I expect the CI tests to fail.  I have not addressed the Firefox 70 issue in this PR which is referenced here: https://github.com/cyclejs/cyclejs/issues/933

**Comment by jvanbruegge** [comment]
@ntilwalli could you rebase onto the current master? The CI is now fixed

**Comment by ntilwalli** [comment]
The firefox 70 issue still happens locally for me. I've rebased and pushed though, crossing fingers that it doesn't happen on CI

**Comment by jvanbruegge** [comment]
Maybe in your local repo snabbdom was not updated, ci passes

**Comment by ntilwalli** [comment]
Yeah, it passed after I updated the libraries.

**Pull request merged**
