### PR TITLE
docs(META): move API docs to docs/content/api

### PR DESCRIPTION
**Pull request by jvanbruegge**
ISSUES CLOSED: #574

The problem is that even with the current master, generating documentation on my PC fails, so i can't test this.
I get this error:
```
/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/dox/lib/dox.js:30
  js = js.replace(/\r\n/gm, '\n');
         ^

TypeError: Cannot read property 'replace' of undefined
  at Object.exports.parseComments (/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/dox/lib/dox.js:30:10)
  at ReadFileContext.callback (/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/markdox/lib/markdox.js:152:23)
  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)
```

### CODE REVIEW

**Comment by staltz** [comment]
Hey @jvanbruegge thanks for this. I think that error may happen because the docs generator is trying to run for `/devtool` too. You can remove the `devtool` from RELEASABLE_PACKAGES and see if that fixes it (don't commit it).

**Comment by jvanbruegge** [comment]
That does not fix it. The error happens for every package:
```
make[1]: Verzeichnis „/home/jan/Dokumente/Programmierprojekte/cyclejs“ wird betreten
node ./docs/.scripts/make-index.js
node ./docs/.scripts/make-documentation.js
node ./docs/.scripts/make-releases.js
node ./docs/.scripts/make-api-index.js
make[2]: Verzeichnis „/home/jan/Dokumente/Programmierprojekte/cyclejs“ wird betreten
/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/dox/lib/dox.js:30
  js = js.replace(/\r\n/gm, '\n');
         ^

TypeError: Cannot read property 'replace' of undefined
  at Object.exports.parseComments (/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/dox/lib/dox.js:30:10)
  at ReadFileContext.callback (/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/markdox/lib/markdox.js:152:23)
  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)

✓ Docs for run
make[2]: Verzeichnis „/home/jan/Dokumente/Programmierprojekte/cyclejs“ wird verlassen

make[2]: Verzeichnis „/home/jan/Dokumente/Programmierprojekte/cyclejs“ wird betreten
/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/dox/lib/dox.js:30
  js = js.replace(/\r\n/gm, '\n');
         ^

TypeError: Cannot read property 'replace' of undefined
  at Object.exports.parseComments (/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/dox/lib/dox.js:30:10)
  at ReadFileContext.callback (/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/markdox/lib/markdox.js:152:23)
  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)

✓ Docs for most-run
make[2]: Verzeichnis „/home/jan/Dokumente/Programmierprojekte/cyclejs“ wird verlassen

make[2]: Verzeichnis „/home/jan/Dokumente/Programmierprojekte/cyclejs“ wird betreten
/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/dox/lib/dox.js:30
  js = js.replace(/\r\n/gm, '\n');
         ^

TypeError: Cannot read property 'replace' of undefined
  at Object.exports.parseComments (/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/dox/lib/dox.js:30:10)
  at ReadFileContext.callback (/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/markdox/lib/markdox.js:152:23)
  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)

✓ Docs for rxjs-run
make[2]: Verzeichnis „/home/jan/Dokumente/Programmierprojekte/cyclejs“ wird verlassen

make[2]: Verzeichnis „/home/jan/Dokumente/Programmierprojekte/cyclejs“ wird betreten
/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/dox/lib/dox.js:30
  js = js.replace(/\r\n/gm, '\n');
         ^

TypeError: Cannot read property 'replace' of undefined
  at Object.exports.parseComments (/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/dox/lib/dox.js:30:10)
  at ReadFileContext.callback (/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/markdox/lib/markdox.js:152:23)
  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)

✓ Docs for jsonp
make[2]: Verzeichnis „/home/jan/Dokumente/Programmierprojekte/cyclejs“ wird verlassen

make[2]: Verzeichnis „/home/jan/Dokumente/Programmierprojekte/cyclejs“ wird betreten
/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/dox/lib/dox.js:30
  js = js.replace(/\r\n/gm, '\n');
         ^

TypeError: Cannot read property 'replace' of undefined
  at Object.exports.parseComments (/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/dox/lib/dox.js:30:10)
  at ReadFileContext.callback (/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/markdox/lib/markdox.js:152:23)
  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)

✓ Docs for isolate
make[2]: Verzeichnis „/home/jan/Dokumente/Programmierprojekte/cyclejs“ wird verlassen

make[2]: Verzeichnis „/home/jan/Dokumente/Programmierprojekte/cyclejs“ wird betreten
/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/dox/lib/dox.js:30
  js = js.replace(/\r\n/gm, '\n');
         ^

TypeError: Cannot read property 'replace' of undefined
  at Object.exports.parseComments (/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/dox/lib/dox.js:30:10)
  at ReadFileContext.callback (/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/markdox/lib/markdox.js:152:23)
  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)

✓ Docs for dom
make[2]: Verzeichnis „/home/jan/Dokumente/Programmierprojekte/cyclejs“ wird verlassen

make[2]: Verzeichnis „/home/jan/Dokumente/Programmierprojekte/cyclejs“ wird betreten
/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/dox/lib/dox.js:30
  js = js.replace(/\r\n/gm, '\n');
         ^

TypeError: Cannot read property 'replace' of undefined
  at Object.exports.parseComments (/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/dox/lib/dox.js:30:10)
  at ReadFileContext.callback (/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/markdox/lib/markdox.js:152:23)
  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)

✓ Docs for html
make[2]: Verzeichnis „/home/jan/Dokumente/Programmierprojekte/cyclejs“ wird verlassen

make[2]: Verzeichnis „/home/jan/Dokumente/Programmierprojekte/cyclejs“ wird betreten
/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/dox/lib/dox.js:30
  js = js.replace(/\r\n/gm, '\n');
         ^

TypeError: Cannot read property 'replace' of undefined
  at Object.exports.parseComments (/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/dox/lib/dox.js:30:10)
  at ReadFileContext.callback (/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/markdox/lib/markdox.js:152:23)
  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)

✓ Docs for http
make[2]: Verzeichnis „/home/jan/Dokumente/Programmierprojekte/cyclejs“ wird verlassen

make[2]: Verzeichnis „/home/jan/Dokumente/Programmierprojekte/cyclejs“ wird betreten
/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/dox/lib/dox.js:30
  js = js.replace(/\r\n/gm, '\n');
         ^

TypeError: Cannot read property 'replace' of undefined
  at Object.exports.parseComments (/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/dox/lib/dox.js:30:10)
  at ReadFileContext.callback (/home/jan/Dokumente/Programmierprojekte/cyclejs/node_modules/markdox/lib/markdox.js:152:23)
  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)

✓ Docs for history
make[2]: Verzeichnis „/home/jan/Dokumente/Programmierprojekte/cyclejs“ wird verlassen

make[1]: Verzeichnis „/home/jan/Dokumente/Programmierprojekte/cyclejs“ wird verlassen
```

**Comment by jvanbruegge** [comment]
`betreten` is enter, `verlassen` is exit

**Comment by staltz** [comment]
Try `__dirname + '/../etcetc`, I think you did `__dirname + '../etcetc`

**Comment by jvanbruegge** [comment]
Yes, I did, but I still get the same errors
I also get the errors on the current master

**Comment by jvanbruegge** [comment]
I dont think it runs that far. Because I cant see [this line](https://github.com/cyclejs/cyclejs/pull/588/files#diff-e6b14735191203407f26edc794489228R22) in the output

**Comment by staltz** [comment]
Oh, it could be that you don't have `js` generated from TypeScript for each lib. `make lib dom` e.g.

**Comment by jvanbruegge** [comment]
ok, yeah, that and removing devtool made it. Maybe include a `make lib all` and run it on `make setup`

It works as expected, documentation is generated normally

**Comment by jvanbruegge** [comment]
Should I filter out `devtool` somehow?

**Comment by staltz** [comment]
> Maybe include a make lib all and run it on make setup

Yes

> Should I filter out devtool somehow?

You could actually just remove it from RELEASABLE_PACKAGES in this PR. I need to anyway figure out the devtools build pipeline properly.

**Comment by jvanbruegge** [comment]
I'll open an issue for the `make lib all`

**Comment by jvanbruegge** [comment]
Anything left to do here?

**Comment by staltz** [comment]
Oh cool, I didn't see your latest commit until now. Yes it looks ready. Also, I'm disappointed with Makefile, for some reason even `make test` (all) stopped working on my local machine.

**Pull request merged**
