### PR TITLE
[Cycle.js Neo] The new state master wrapper

### PR DESCRIPTION
**Pull request by jvanbruegge**
This will be the first master wrapper from Cycle.js side and test the interaction of APIs without drivers

### CODE REVIEW

**Comment by jvanbruegge** [comment]
Again, having a test suite was really valuable, because while my initial implementation worked, there were two details (the state source filtering out duplicate and undefined values and the default lens handling arrays) that I did not know about in the current implementation.
The tests caught those two and it was easy to fix.

**Comment by jvanbruegge** [comment]
@staltz The `withState` part is now 100% done. Now only the collection stuff is missing for this to be merged

**Comment by jvanbruegge** [comment]
This took me a while to debug, but I have a `makeCollection` implementation now. And AFAICT it should be even more performant than the current one (less allocation and better asymptotics)

**Comment by jvanbruegge** [comment]
The new `pickMerge` implementation is A LOT longer than the old one, but before we had issues that once a new set of sinks was emitted, a new `merge()` call would be issued, causing it to resubscribe to the sinks, which in turn triggered the calls to `of` again. Also I had to change the replay subject to be an explicit async loop breaker. Having this here is temporary, I will open a PR on the callbags repo

**Comment by staltz** [comment]
:clap: For implementing pickMerge with callbags, this one was one of the hardest ones to implement with xstream. Because of that, it's fine if it's longer, as long as you intend to do https://github.com/cyclejs/callbags/pull/31

I only have one feedback, and that's about the public API for `withState`. It used to be `withState(main, name)` now it seems to be curried and there's also an `initialState`. In issue https://github.com/cyclejs/cyclejs/issues/948 I expressed concern that `withState` should not receive a state argument, because it's app logic and `withState` is basically never used inside `main()`, it's often used outside, together with `run` and drivers.

It's indeed really helpful to have tests, and I'm happy with the implementation, looks good.

**Comment by jvanbruegge** [comment]
> as long as you intend to do cyclejs/callbags#31

What does the subject have to do with `pickMerge`? The new async subject is used in `withState`.

> hat's about the public API for `withState`

It needs to be curried (with `main` coming second) because usually main is supplied by `run`, not the user. But yeah I can remove the initial state, I don't really care. Would be `withState(name?)(main)` then (or with `run`: `run(main, [withState(name)])`)

**Comment by staltz** [comment]
> The new async subject is used in `withState`.

Oh, my mistake, indeed asyncSubject is not for pickMerge.

> It needs to be curried (with `main` coming second) because usually main is supplied by `run`, not the user.

Right! MasterWrapper type was `(main: Main) => Main`. So yes for the currying.

> But yeah I can remove the initial state, I don't really care. Would be `withState(name?)(main)` then (or with `run`: `run(main, [withState(name)])`)

Ok, yes, that's how it should be.

**Comment by jvanbruegge** [comment]
Looking further over the tests: https://github.com/cyclejs/cyclejs/blob/master/state/test/makeCollection.ts#L282

Is this something we actually want to support? Because IMO collection should just error if it does not get an array instead basically doing the job of a `get: x => [x], set: (_, [x]) => x` lens

**Comment by staltz** [comment]
Hmm, I don't quite remember why that's there. I'm inclined to not support it, but before that, let me take some time to look at the history:

- https://github.com/staltz/cycle-onionify/commit/4a3c0264e7ac9d6cdabc526380669ee3a7ec04be
- https://github.com/staltz/cycle-onionify/issues/28

**Comment by staltz** [comment]
Here's one at least: 

https://github.com/staltz/cycle-onionify/issues/28#issuecomment-303383735

> We could even consider expanding the semantics of sources.onion.asCollection to work when sources.onion.state$ is not a Stream<Array<T>> (currently it would crash, I guess). If sources.onion.state$ is something like Stream<object>, then sources.onion.asCollection(Item, sources) would create just one Item. I don't think there is practical utility for this, except it avoids one runtime crash and makes the API more resistant.

**Comment by staltz** [comment]
And https://github.com/staltz/cycle-onionify/issues/28#issuecomment-303388405 :smile:

**Comment by staltz** [comment]
Here's another argument in favor of it: https://github.com/staltz/cycle-onionify/issues/28#issuecomment-304870890 but in hindsight I don't think that's a good enough argument, we can still implement what we need even if collection only supports `Stream<Array<T>>`

@jvanbruegge I'd say let's remove it. It hasn't served us in 4 years, so that's a sign. Your intuition back then was right. :)

**Comment by jvanbruegge** [comment]
> Your intuition back then was right. :)

There is a lot of other stuff in that thread I do not agree with any more (mainly being able to pass a lens to isolate to avoid creating a list component)

**Comment by jvanbruegge** [comment]
> I'd say let's remove it

The diff in the test is quite small even without this feature:
Before:
```ts
const wrapperSinks = isolate(Wrapper, 'wrap')(sources);
```
After:
```ts
const wrapLens = {
  get: (x: any) => [x.wrap],
  set: (x: any, y: any) => ({ ...x, wrap: y[0] }),
};

const wrapperSinks = isolate(Wrapper, wrapLens)(sources);
```

The test still does not pass, but that's another issue that I have to find

**Comment by jvanbruegge** [comment]
Ok, found the issue (actually two issues). First I need to pass `{ state: wrapLens, '*': null }` to `isolate`. So I added a new error message to `isolate` because I expect others to run into the same issue.
The second issue is one with the new async subject: https://github.com/cyclejs/callbags/pull/32
Also, to test that the collection throws an error I had to extend the error reporting mechanism to APIs, which is good anyways.

**Comment by jvanbruegge** [comment]
Ok, all the old tests pass now, but we definitely need more tests than we have at the moment. So what's left to do here now:
-[ ] Change `pickCombine` to work like `pickMerge` (avoid resubscribing)
-[ ] Use asyncSubject from `@cycle/callbags` (requires https://github.com/cyclejs/callbags/pull/32 to be merged)
-[ ] Add more tests, especially add some tests for `pickCombine`

**Comment by jvanbruegge** [comment]
Updated all the dependencies (including `@cycle/callbags`) so the second point in that todo list is now done. Minireq and callbags had breaking changes that needed changes to the code, so I put them in seperate commits for easier review

**Comment by jvanbruegge** [comment]
Ok, I managed to create a higher order `pick` function, that is then used to implement `pickMerge` and `pickCombine`. But even with that complexity gone, `pickCombine` is still not trivial.

**Comment by jvanbruegge** [comment]
So, and with these tests added this is ready :tada:

**Review by staltz — APPROVED** [review]
Reviewed, some of the tests gave me a mind twist, but looked correct. Thanks for the massive progress! :clap:

**Pull request merged**
